apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mvaldron-test 
  janus-idp.io/tekton: mvaldron-test
  backstage.io/kubernetes-id: mvaldron-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mvaldron-test
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  